### ISSUE TITLE
Confused with Volumetric Intersection Calculation in get_DVO and get_PLI  within metrics.py

### ISSUE THREAD

**Issue by 1874Mercury** [jivankandel/PUResNet#11]
In the get_DVO and get_PLI functions within metrics.py, the volumetric intersection between the predicted pocket and the actual pocket or ligand is computed. However, in the create_3d_grid function, the 3D grid is constructed relative to the minimum coordinates of their respective points, not a common reference point. This results in a volumetric intersection that does not reflect the true intersection, as the two 3D grids are not built based on the same reference point. Have I misunderstood something here?

**Comment by jivankandel** [comment]
Before calculating these metrics, the pocket coordinates should be normalized according to the protein structure center.

**Comment by 1874Mercury** [comment]
Got it! Thx!
