### ISSUE TITLE
What other steps should be taken ahead now? getting error as could not open whole_trained_model.hdf

### ISSUE THREAD

**Issue by vishal-farande** [jivankandel/PUResNet#12]
I had entered code as  `python predict.py -ftype pdb -m 0 -i /Users/vishalfarande/Downloads/PUResNet-main/coach420/966c/protein.pdb -mpath whole_trained_model1.hdf -otype mol2 -o output -gpu 1`

further I got something like 
2023-11-27 17:59:12.927852: W tensorflow/core/util/tensor_slice_reader.cc:97] Could not open whole_trained_model1.hdf: DATA_LOSS: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is /Users/vishalfarande/Downloads/PUResNet-main/coach420/966c/protein.pdb)

2023-11-27 17:59:13.183370: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
1/1 [==============================] - 1s 742ms/step
/Users/vishalfarande/anaconda3/envs/Puresnet/lib/python3.11/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')

**Comment by jivankandel** [comment]
Dear bishal-farande, whole_trained_model1.hdf this file is uploded through git-lfs, you need to download file from github. Cloning wont work in this case.
