### ISSUE TITLE
The sha256sum does not match

### ISSUE THREAD

**Issue by khoroshyy** [jivankandel/PUResNet#13]
sha256sum whole_trained_model1.hdf
Output: 63f3f3321ab6fe58d824518185b821380ee2674369209d025c52489f29c18466
while i get 
 sha256sum whole_trained_model1.hdf
4f8ed4840be8ac934bf07e2e40cca734311523e11d3ff2b0bf88ea349a5ce9b6  whole_trained_model1.hdf

**Comment by jivankandel** [comment]
@khoroshyy, yo need to download the model from githug cloning wont download the model beacuse model was uploded through git lfs. If the error persist, then check the h5py version. The required version is h5py=2.10.0.

**Comment by khoroshyy** [comment]
I did download the model.
I will check h5py.
