### ISSUE TITLE
current tfbio version out of date

### ISSUE THREAD

**Issue by rcooperbaer** [jivankandel/PUResNet#3]
`conda install -c cheminfibb tfbio` does not work, manual install of package results in clashing dependencies

**Comment by jivankandel** [comment]
Can you provide me with the details so I can fix it for you?

**Comment by jivankandel** [comment]
I found out the problem, was caused due to open babel package, since they have updated their package I need to integrate that package. Give me some time to fix the problem. Hope for your understanding.

**Comment by jivankandel** [comment]
Solved!!!!
