### ISSUE TITLE
structure id in k-fold cross validation

### ISSUE THREAD

**Issue by ckami12138** [jivankandel/PUResNet#5]
Hello, I want to train a new model on your scpdb subset. Can you give me the structure id in each fold, so I can optimize my model? Thanks.

**Comment by jivankandel** [comment]
(http://ftp.ebi.ac.uk/pub/databases/Pfam/mappings/pdb_pfam_mapping.txt), you can use this to map the PDB to Pfam id and make sure to use [sklearn.model_selection.StratifiedKFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html) to split into train and test where each PDB belonging to the same Pfam stays in either train or test.

**Comment by ckami12138** [comment]
Thanks for your quick response, I will try it later.

**Comment by ckami12138** [comment]
Could you tell me the number of steps_per_epoch in your work please, I eveluate the training time if I use the numbers used in kalasanty paper, which is 10000 epoches , 150 steps per epoch and 10 batch-size, it will take 10 days to train a model. So, I will really appreciate if you can tell me the steps per epoch  when you train your final model.

**Comment by jivankandel** [comment]
I used early stopping while training you can use that.
