### ISSUE TITLE
Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is xx.pdb)

### ISSUE THREAD

**Issue by BinhongLiu** [jivankandel/PUResNet#6]
Hi, really excellent tool! 
I tried to run PUResNet using CPU in Linux. But there were some warnings and errors. Should I deal with these warnings?
1. FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'
2. 2023-02-12 10:46:24.016877: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
3. *** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is 3srq.pdb)
4. 2023-02-12 10:46:29.889874: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.

The output folder was created but nothing was there. So I used another .cif structure (AF-A0A844RNM1-F1-model_v3.cif) from the alphafold2 database for the test and only one file (pocket0.mol2) was created. Was the PUResNet properly executed? 

[test.zip](https://github.com/jivankandel/PUResNet/files/10715200/test.zip)
Many thanks

The log.

(PUResNet) [ac1daawz21@login04 PUResNet-main]$ python predict.py -ftype pdb -m 0 -i ../3srq.pdb -mpath whole_trained_model1.hdf -otype mol2 -o output
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
2023-02-12 10:44:04.324446: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-02-12 10:44:04.324856: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is ../3srq.pdb)

2023-02-12 10:44:10.089050: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-02-12 10:44:10.106696: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-02-12 10:44:10.298308: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-02-12 10:44:10.317569: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
(PUResNet) [ac1daawz21@login04 PUResNet-main]$ cp ../3srq.pdb ./
(PUResNet) [ac1daawz21@login04 PUResNet-main]$ python predict.py -ftype pdb -m 0 -i 3srq.pdb -mpath whole_trained_model1.hdf -otype mol2 -o output
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/work/home/ac1daawz21/miniconda3/envs/PUResNet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
2023-02-12 10:46:24.016877: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-02-12 10:46:24.017268: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is 3srq.pdb)

2023-02-12 10:46:29.889874: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-02-12 10:46:29.907867: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-02-12 10:46:30.101277: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-02-12 10:46:30.120798: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.

**Comment by jivankandel** [comment]
incase output is provided, then it is executing properly, but the concern is TensorFlow version you are using. Can you check the recommended tensorflow version and the one you are using. Also our new tool is being developed for same task. You can also try https://nsclbio.jbnu.ac.kr/tools/jmol, for some experiments. This has better results and is on development phase. Sorry for late response.

**Comment by BinhongLiu** [comment]
Thank you!
The version of TensorFlow that has been installed is the same as the recommended one (1.11). In fact, I plan to predict the pockets of many protein structures, so I'd like to use a standalone tool for the prediction. Also, I found that the output is actually one .pdb file of the cavity. Could PUResNet output one .pdb file of the binding sites (residues) around the cavity? Thanks.

**Comment by jivankandel** [comment]
This version of our PURESNET is developed to predict the cavity not the binding residues around the Cavity. But the method that we are developing now PURESNET V2.0 is able to predict binding residues. I suggest you to experiment on https://nsclbio.jbnu.ac.kr/tools/jmol. Although the method is not published yet but trust me the results are fare more accurate then PURESNET V1.0

**Comment by BinhongLiu** [comment]
Yes, the V2.0 is really cool! Could it be run in Linux as a standalone tool? Can't wait to use it.

**Comment by jivankandel** [comment]
i will release the standalone tool when i publish my paper which might take little bit more time. But the web version you can use anytime.
